### ISSUE TITLE
Overriding a single model requires calling createHttpModel() from within the overridden FreshBooksClient, instead of just using $this->httpClient

### ISSUE THREAD

**Issue by davidbankes** [amcintosh/freshbooks-php-sdk#22]
I needed a client field (username) which the default model doesn't include. It's a deprecated field, so I didn't think it warranted its own pull request.

So I overrode the `FreshbBooksClient` so I could override the public `clients()` method and insert a custom model (which extended the base and just added another public property).

The original method looks like this:
```
   public function clients(): AccountingResource
    {
        return new AccountingResource($this->httpClient, 'users/clients', Client::class, ClientList::class);
    }
```

$this->httpClient is a private property, so the extension didn't have access to it. I called $this->createHttpClient() in that place, and everything seems to be working perfectly. But it feels like that should maybe be a protected property to make it easier to reuse the same httpClient in my extension.

Anyway this is no big deal. I'm really enjoying the package and it's saving me a lot of time. If you're interested in this change, I could also submit a PR. If you're not interested, that's fine; just go ahead and close this issue.

Thanks so much for this package!

**Comment by amcintosh** [comment]
Hi! 
Thanks for the input! 

It sounds reasonable to me to switch it to a protected field. Happy to get a PR.
