### ISSUE TITLE
What is the support status of this repo?

### ISSUE THREAD

**Issue by JoeMurray** [amcintosh/freshbooks-php-sdk#41]
I see that Freshbooks calls this a community library https://www.freshbooks.com/api/libraries , but note the ReadMe says 'FreshBooks users are uniquely identified by their email across **our** entire product.' The repo seems to have only a single contributor but to be very professional and actively under development/maintained. 

I'd like to use it but don't want to get tied into an abandoned library. What is the status of @amcintosh 's or others' commitment to maintaining and developing this PHP SDK for Freshbooks?

**Comment by amcintosh** [comment]
Hi. 
Thanks for the question and I hope I can clarify.

This library is not currently directly supported by FreshBooks. While I am a FreshBooks employee, this was built on my own time. 

I am actively working on it and intend to maintain it but as this isn't my full-time job I can't guarantee anything support-wise. I hope that if it gets active users that it can be supported by more than just me. 

As the API team at FreshBooks grows it is possible that it may get adopted internally (as the [Python SDK did](github.com/freshbooks/freshbooks-python-sdk), but there are no immediate plans for that to my knowledge. 

Thanks again for the question. I'll update the README to better reflect this.

**Comment by JoeMurray** [comment]
Great answer. We now have confidence to move forward with incorporating this into our workflow.
