### ISSUE TITLE
taxNumber1 Issue when creating an Invoice

### ISSUE THREAD

**Issue by jeffwaddell** [amcintosh/freshbooks-php-sdk#51]
When creating an invoice - it returns the following error 

_Write access denied. Tried to write None to field taxNumber1 of object line_

Per Freshbooks Support - we aren't supposed to send/try to set taxNumber1 or taxNumber2

**Comment by amcintosh** [comment]
Hi!
Thanks for finding the issue and opening the ticket.

So it looks like that is a change in the FreshBooks API. The field was not read-only before. 

I'll put up a change to not write that field.

**Comment by amcintosh** [comment]
I've updated and published a new release. Thanks again.
