### ISSUE TITLE
Does the API support setting invoice payment options?

### ISSUE THREAD

**Issue by bhaidar** [amcintosh/freshbooks-php-sdk#60]
Hi,

Thank you for this great API.

I wonder if this API allows me to set the payment options on an invoice once created.

Thank you
Bill

**Comment by amcintosh** [comment]
Hi,

Thanks for the interest. This SDK doesn't currently support payment options on an invoice, but I'll take a look at fixing that.

Andrew

**Comment by amcintosh** [comment]
Added in v. 0.7.0. Let me know if there are any issues.

**Comment by bhaidar** [comment]
Thanks @amcintosh I will give it a try. Much appreciated.

**Comment by bhaidar** [comment]
@amcintosh Working perfect! Thank you


I wonder if I an connect to WebHooks using this package? Is there an example maybe to share. Thank you
