### ISSUE TITLE
Can I use this library for WebHooks too?

### ISSUE THREAD

**Issue by bhaidar** [amcintosh/freshbooks-php-sdk#63]
Hi @amcintosh 

First of all, does this package support WebHooks? Is there a sample code that first verifies and then listens to WebHook events from FreshBooks?

Thanks
Bill

**Comment by amcintosh** [comment]
Hi!

So the library does support the registration and verification of callbacks.
See https://amcintosh.github.io/freshbooks-php-sdk/html/classes/amcintosh-FreshBooks-FreshBooksClient.html#method_callbacks
and https://amcintosh.github.io/freshbooks-php-sdk/html/classes/amcintosh-FreshBooks-Resource-EventsResource.html#method_verify

There's no example code at the moment, nor examples on checking the verification header, though the [FreshBooks API docs](https://www.freshbooks.com/api/webhooks) does have a python example of that:

```python
# Using Flask:
import base64
import hmac
import hashlib
import json

from flask import Flask, request

def signature_match(verifier, request):
    signature = request.headers.get('X-FreshBooks-Hmac-SHA256')
    data = json.dumps(request.form)

    dig = hmac.new(
        verifier.encode('utf-8'),
        msg=data.encode('utf-8'),
        digestmod=hashlib.sha256
    ).digest()
    calculated_sig = base64.b64encode(dig).decode()

    return signature == calculated_sig
```

I can look into writing a PHP example.

**Comment by amcintosh** [comment]
@bhaidar I've added a [webhooks example](https://github.com/amcintosh/freshbooks-php-sdk/tree/main/examples) and some [more documentation](https://amcintosh.github.io/freshbooks-php-sdk/html/guide/webhooks.html#webhook-callbacks) on their use in [this PR](https://github.com/amcintosh/freshbooks-php-sdk/pull/64).

Hope that helps.
